"""empty message

Revision ID: 07aab36aeb23
Revises: bc61b56eaad6
Create Date: 2022-12-12 19:53:05.145287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07aab36aeb23'
down_revision = 'bc61b56eaad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kisi',
    sa.Column('kisi_id', sa.Integer(), nullable=False),
    sa.Column('kisi_ad', sa.String(), nullable=True),
    sa.Column('kisi_soyad', sa.String(), nullable=True),
    sa.Column('telefon', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('adres', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('kisi_id'),
    sa.UniqueConstraint('telefon')
    )
    with op.batch_alter_table('kargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kargo_alici_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kargo_gonderici_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'kisi', ['kargo_gonderici_id'], ['kisi_id'])
        batch_op.create_foreign_key(None, 'kisi', ['kargo_alici_id'], ['kisi_id'])
        batch_op.drop_column('kargo_gonderici')
        batch_op.drop_column('kargo_alici')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kargo_alici', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kargo_gonderici', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('kargo_gonderici_id')
        batch_op.drop_column('kargo_alici_id')

    op.drop_table('kisi')
    # ### end Alembic commands ###
